image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  project: "Parser"
  tests: "Tests"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  variables:
    test_path: "$tests"
  script:
    - "cd $test_path"
    - "dotnet test"